version: '3.8'

services:
  api:
    build: .
    volumes:
      - .:/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    networks:
      - task-api
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - task-api

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - task-api

networks:
  task-api:
    driver: bridge

volumes:
  db-data:
